version: 0.0.0.{build}
image: Visual Studio 2019
shallow_clone: true
configuration: Release
platform: Any CPU
environment:
  SONARQUBE_TOKEN:
    secure: jD8yc9tSVznJZlP2a70DtOy4/eC6Ld4A0J1GH/7xjs7mWrrlKqeTIWk6BGR7eFv0
  CODECOV_TOKEN:
    secure: TkNT/U61mrXkNbtNjTxKXnBmF3wzp8YcFqAiboRXi8bj61fYHdogm/DxHxIJEtiH
  NUGET_TOKEN:
    secure: HvTOTogb8inLCFQGzXObBrjsWHvZ1OI43nbHcrhfUqb9tVT+0TX7B9H4OXjfowPh
services: 
  - mssql2017
build_script:
  - ps: dotnet tool restore
  - ps: dotnet fake build
test: off