version: 0.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  SONARQUBE_TOKEN:
    secure: jD8yc9tSVznJZlP2a70DtOy4/eC6Ld4A0J1GH/7xjs7mWrrlKqeTIWk6BGR7eFv0
  CODECOV_TOKEN:
    secure: TkNT/U61mrXkNbtNjTxKXnBmF3wzp8YcFqAiboRXi8bj61fYHdogm/DxHxIJEtiH
services: 
  - mssql2014
build_script:
  - ps: ./build/fake.cmd build
after_build:
  - ps: ./buildscripts/afterbuild.ps1
before_test:
  - ps: ./buildscripts/beforetest.ps1
test_script:
  - ps: ./buildscripts/test.ps1
after_test:
  - ps: ./buildscripts/aftertest.ps1
deploy:
  - provider: NuGet
    api_key:
      secure: osLMSCVxKNTsqSX5/7N1A1YRWeGVShtYhco2cdiTfPIahSN5zrEUqpmJu1QCRr0Z
    artifact: /.*\.nupkg/
    on:
      branch: master