version: 0.0.0.{build}
image: Visual Studio 2017
shallow_clone: true
configuration: Release
platform: Any CPU
environment:
  SONARQUBE_TOKEN:
    secure: jD8yc9tSVznJZlP2a70DtOy4/eC6Ld4A0J1GH/7xjs7mWrrlKqeTIWk6BGR7eFv0
  CODECOV_TOKEN:
    secure: TkNT/U61mrXkNbtNjTxKXnBmF3wzp8YcFqAiboRXi8bj61fYHdogm/DxHxIJEtiH
  NUGET_TOKEN:
    secure: 1LgbIbX85nwAiw/QI4PTcJ8JfKZUuSG8ta+H9RevK798l+wY4TvkgKVu5t8+rRxh
services: 
  - mssql2014
build_script:
  - ps: ./build/fake.cmd build
test: off
